WARNING  urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdf21366920>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/ac81092ea0663ab08d44674463c37387/element
WARNING  urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdf213669e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/ac81092ea0663ab08d44674463c37387/element
WARNING  urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdf21366b90>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/ac81092ea0663ab08d44674463c37387/element