{"uuid": "74e8832e-70cf-4901-8cf7-5b376941ca2f", "children": ["c929bf89-6adb-4381-aded-dffe32cae8e3"], "befores": [{"name": "get_webdriver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Service chromedriver unexpectedly exited. Status code was: -9\n\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/_pytest/fixtures.py\", line 1129, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/_pytest/fixtures.py\", line 908, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/Users/maksim/PycharmProjects/LTA_TESTS/Test_Cases/conftest.py\", line 24, in get_webdriver\n    driver = webdriver.Chrome(options=options)\n  File \"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py\", line 73, in __init__\n    self.service.start()\n  File \"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/common/service.py\", line 98, in start\n    self.assert_process_still_running()\n  File \"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/common/service.py\", line 109, in assert_process_still_running\n    raise WebDriverException(\n"}, "start": 1678792018299, "stop": 1678792028356}], "start": 1678792018299, "stop": 1678792028520}