{"uid":"5254eb751efafefd","name":"test_homepage2","fullName":"Test_Cases.test_homepage.TestHomepage#test_homepage2","historyId":"30dde2a0f0148704bfa9d9d33a98c7e1","time":{"start":1690975072396,"stop":1690975072396,"duration":0},"status":"broken","statusMessage":"ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/115.0.5790/chromedriver_linux64.zip","statusTrace":"request = <SubRequest 'get_webdriver' for <Function test_homepage>>\nget_chrome_options = <selenium.webdriver.chrome.options.Options object at 0x7f9d3ca18160>\n\n    @pytest.fixture(scope='session')\n    def get_webdriver(request, get_chrome_options):\n        options = get_chrome_options\n>       driver = webdriver.Chrome(ChromeDriverManager().install(), options=options)\n\nTest_Cases/conftest.py:34: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/webdriver_manager/chrome.py:39: in install\n    driver_path = self._get_driver_path(self.driver)\n/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/webdriver_manager/core/manager.py:30: in _get_driver_path\n    file = self._download_manager.download_file(driver.get_url())\n/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/webdriver_manager/core/download_manager.py:28: in download_file\n    response = self._http_client.get(url)\n/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/webdriver_manager/core/http.py:33: in get\n    self.validate_response(resp)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nresp = <Response [404]>\n\n    @staticmethod\n    def validate_response(resp: requests.Response):\n        status_code = resp.status_code\n        if status_code == 404:\n>           raise ValueError(f\"There is no such driver by url {resp.url}\")\nE           ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/115.0.5790/chromedriver_linux64.zip\n\n/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/webdriver_manager/core/http.py:16: ValueError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"get_chrome_options","time":{"start":1690975069333,"stop":1690975069333,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"get_webdriver","time":{"start":1690975069334,"stop":1690975072348,"duration":3014},"status":"broken","statusMessage":"ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/115.0.5790/chromedriver_linux64.zip\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/pluggy/_callers.py\", line 80, in _multicall\n    res = hook_impl.function(*args)\n  File \"/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1129, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 908, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/home/runner/work/LTA_TESTS/LTA_TESTS/Test_Cases/conftest.py\", line 34, in get_webdriver\n    driver = webdriver.Chrome(ChromeDriverManager().install(), options=options)\n  File \"/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/webdriver_manager/chrome.py\", line 39, in install\n    driver_path = self._get_driver_path(self.driver)\n  File \"/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/webdriver_manager/core/manager.py\", line 30, in _get_driver_path\n    file = self._download_manager.download_file(driver.get_url())\n  File \"/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/webdriver_manager/core/download_manager.py\", line 28, in download_file\n    response = self._http_client.get(url)\n  File \"/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/webdriver_manager/core/http.py\", line 33, in get\n    self.validate_response(resp)\n  File \"/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/webdriver_manager/core/http.py\", line 16, in validate_response\n    raise ValueError(f\"There is no such driver by url {resp.url}\")\n","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":true,"hasContent":true}],"afterStages":[],"labels":[{"name":"parentSuite","value":"Test_Cases"},{"name":"suite","value":"test_homepage"},{"name":"subSuite","value":"TestHomepage"},{"name":"host","value":"fv-az362-960"},{"name":"thread","value":"2198-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"Test_Cases.test_homepage"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":6,"skipped":0,"passed":0,"unknown":0,"total":6},"items":[{"uid":"d2e24bef15382aac","reportUrl":"https://MaximKrivenko.github.io/LTA_TESTS/37//#testresult/d2e24bef15382aac","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x55b34f07c783 <unknown>\n#1 0x55b34eda8917 <unknown>\n#2 0x55b34edd3978 <unknown>\n#3 0x55b34edd09c9 <unknown>\n#4 0x55b34ee10a13 <unknown>\n#5 0x55b34ee1015f <unknown>\n#6 0x55b34ee07bd3 <unknown>\n#7 0x55b34eddba7b <unknown>\n#8 0x55b34eddc81e <unknown>\n#9 0x55b34f03de98 <unknown>\n#10 0x55b34f041d67 <unknown>\n#11 0x55b34f04c32c <unknown>\n#12 0x55b34f042993 <unknown>\n#13 0x55b34f011827 <unknown>\n#14 0x55b34f0668a8 <unknown>\n#15 0x55b34f066a36 <unknown>\n#16 0x55b34f0755f3 <unknown>\n#17 0x7f282c34ab43 <unknown>","time":{"start":1690974900219,"stop":1690974900219,"duration":0}},{"uid":"8481d5d4310ecc1e","reportUrl":"https://MaximKrivenko.github.io/LTA_TESTS/36//#testresult/8481d5d4310ecc1e","status":"broken","statusDetails":"AttributeError: 'WebDriver' object has no attribute 'switch_to_window'","time":{"start":1690973697166,"stop":1690973704027,"duration":6861}},{"uid":"36494b5c0a412bfc","reportUrl":"https://MaximKrivenko.github.io/LTA_TESTS/35//#testresult/36494b5c0a412bfc","status":"broken","statusDetails":"ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/115.0.5790/chromedriver_linux64.zip","time":{"start":1690973260119,"stop":1690973260119,"duration":0}},{"uid":"9a0efac3473e86fb","reportUrl":"https://MaximKrivenko.github.io/LTA_TESTS/34//#testresult/9a0efac3473e86fb","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_TIMED_OUT\n  (Session info: headless chrome=115.0.5790.110)\nStacktrace:\n#0 0x5606d2d87783 <unknown>\n#1 0x5606d2ab3917 <unknown>\n#2 0x5606d2aab989 <unknown>\n#3 0x5606d2a9af52 <unknown>\n#4 0x5606d2a9c68b <unknown>\n#5 0x5606d2a9b32d <unknown>\n#6 0x5606d2a9a2ec <unknown>\n#7 0x5606d2a9a25e <unknown>\n#8 0x5606d2a98f1a <unknown>\n#9 0x5606d2a9936a <unknown>\n#10 0x5606d2ab57d0 <unknown>\n#11 0x5606d2b2b885 <unknown>\n#12 0x5606d2b12e02 <unknown>\n#13 0x5606d2b2b0d9 <unknown>\n#14 0x5606d2b12bd3 <unknown>\n#15 0x5606d2ae6a7b <unknown>\n#16 0x5606d2ae781e <unknown>\n#17 0x5606d2d48e98 <unknown>\n#18 0x5606d2d4cd67 <unknown>\n#19 0x5606d2d5732c <unknown>\n#20 0x5606d2d4d993 <unknown>\n#21 0x5606d2d1c827 <unknown>\n#22 0x5606d2d718a8 <unknown>\n#23 0x5606d2d71a36 <unknown>\n#24 0x5606d2d805f3 <unknown>\n#25 0x7fe15aef0b43 <unknown>","time":{"start":1690972630800,"stop":1690972630800,"duration":0}},{"uid":"46218c80454347c","reportUrl":"https://MaximKrivenko.github.io/LTA_TESTS/33//#testresult/46218c80454347c","status":"broken","statusDetails":"ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/115.0.5790/chromedriver_linux64.zip","time":{"start":1690971483239,"stop":1690971483239,"duration":0}}]},"tags":[]},"source":"5254eb751efafefd.json","parameterValues":[]}